[project]
name = "ttcs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain-text-splitters>=0.3.9",
    "pydantic>=2.10.0",
]
